version: '2.2'


networks:
  elastic:
    driver: bridge

services:
  postgres_enron:
    restart: always
    image: postgres:12
    environment:
      - DEBUG=false

      - POSTGRES_USER=postgres
      - DB_PASS=postgres
      - POSTGRES_DB=enron

    volumes:
      - ../databases/pg/enron/data:/var/lib/postgresql
    ports:
      - "5432:5432"

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
    container_name: elastic
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ../databases/elastic/enron/data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic
