version: '2.2'


networks:
  elastic:
    driver: bridge

services:
  postgres_enron:
    restart: always
    image: postgres:12
    environment:
      - DEBUG=false

      - POSTGRES_USER=postgres
      - DB_PASS=postgres
      - POSTGRES_DB=enron

    volumes:
      - ../databases/pg/enron/data:/var/lib/postgresql
    ports:
      - "5432:5432"

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
    container_name: elastic
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - http.cors.enabled=true
      - http.cors.allow-origin=http://localhost:1358,http://127.0.0.1:1358
      - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
      - http.cors.allow-credentials=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ../databases/elastic/data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic
    
  tika:
    image: logicalspark/docker-tikaserver
    ports:
      - 9998:9998

